HeapsIO/heaps

hxd/res/FileTree.hx

`FileTree.scanRec` currently only ignores directory names beginning with `'.'` or `'_'`. It should also ignore file names beginning with those characters. (It crashes when encountering file names beginning with `'.'`)

Ignore files/directories starting with . or _

---

h2d/SpriteBatch.hx

Bounds for a non scaled / rotated SpriteBatch only got calculated with the tile that is used to initialize the SpriteBatch.
Instead the tiles of the batch elements should be used to calculate the bounds. ;)
I do not like the fact that we have to pass a Tile to create a SpriteBatch. Instead we could pass the texture / atlas? It is a bit confusing when you first look at how it's done. Suggestions?

Fixed a bug in SpriteBatch bounds calculation

---

h3d/impl/MemoryManager.hx
samples/draw/Draw.hx

Instantiating h2d.Graphics every frame causes the MemoryManager to run out of buffers eventually because they will never get disposed of.
Crashes after a while on Firefox and Chrome.

Fix the draw sample

---

h2d/Anim.hx

create the Anim instance,then set the frames after atlas source loaded in a later time,the frames.length equals 0,"curFrame %= frames.length" make curFrame to NaN,so the anim stoped on the first  
frame.

fix Anim not work when set frames in a later time.

---

h3d/impl/GlDriver.hx

- Create and bind a VertexArray during init
- Fix GLSL #version (130 - 150). OSX core profile requires 3.2+ version (GLSL 150)
- Call glBindFragDataLocation for fragment shader outputs
- Reset boundTextures cache in setRenderTarget()

Gl misc fixes

---

hxd/snd/NativeChannel.hx

When I compile with OpenFL (4.7.3) / Lime (3.7.2), I've the following errors:
```/home/Pi/haxelib/heaps/git/hxd/snd/NativeChannel.hx:37: characters 12-14 : Warning : The lime.audio package has been moved to lime.media.*
/home/Pi/haxelib/heaps/git/hxd/snd/NativeChannel.hx:38: characters 8-10 : Warning : The lime.audio package has been moved to lime.media.*
/home/Pi/haxelib/heaps/git/hxd/snd/NativeChannel.hx:39: characters 2-4 : Warning : The lime.audio package has been moved to lime.media.*
/home/Pi/haxelib/heaps/git/hxd/snd/NativeChannel.hx:39: characters 17-25 : Warning : The lime.audio package has been moved to lime.media.*
/home/Pi/haxelib/heaps/git/hxd/snd/NativeChannel.hx:40: characters 2-4 : Warning : The lime.audio package has been moved to lime.media.* …
```

Fix error "Warning : The lime.audio package has been moved to lime.media.*"

---

hxd/snd/Driver.hx
hxd/snd/effect/Spatialization.hx

Set SOURCE_RELATIVE to true on non-spatialized channels. 
Mono sounds where spatialized even without the Spatialization effect added on the channel.

fix non-spatialized mono

---

hxd/fs/LocalFileSystem.hx

`sys.FileSystem.fullPath` returns null if the path doesn't exist on HL/mac.

Fix for fullPath

---

h2d/Scene.hx
samples/Interactive.hx

Not sure if `globalToLocal` was originally avoided for performance reasons, but this seems to work well.
I've also modified the `Interactive` sample to test combinations of scene rotation and interactive rotation + scaling, as well as testing the `getInteractive` function.

Take rotation into account for mouseX/Y and event handling in Scene (fixes #51 and #144)

---

hxd/fs/LocalFileSystem.hx

Resulting in the concatenation of the already absolute path `exePath` and `baseDir` and then `Uncaught exception Failure("get_full_path")` when calling `hxd.Res.initEmbed()`.

Haxe 4 eval will return the main class' path as programPath

---

h2d/CachedBitmap.hx
h3d/Engine.hx
h3d/impl/DirectXDriver.hx
hxd/fs/LocalFileSystem.hx
hxsl/HlslOut.hx

- Avoid texture creation in `CachedBitmap` if width or height is zero (fails on DirectX)
- Call flushTarget() before driver.setRenderZone() (`GlDriver` uses `curTarget.height` in setRenderZone)
- Check `FileSystem.exists` before `isDirectory` (isDirectory throws an exception if destination is not accessible)
- Other minor DirectX fixes

Misc Fixes 

---

hxsl/Checker.hx

The error-call tries to do `e.pos`, which isn't gonna work if `e == null`.
This can be reproduced by having a plain `return` in a shader function that is declared to return something.

fix null access in hxsl.Checker on bad return

---

hxsl/Ast.hx
hxsl/Checker.hx

SmoothStep didnt work on JS and HL/DirectX for me.
But works when using **s**tep with lower case.

SmoothStep should be Smoothstep

---

h2d/Text.hx
samples/Text.hx

Text.textWidth returns calcWidth and not maxWidth.
One more test case in Text sample.

Fix Text.getBounds calculation being icorrect when yMin is negative.

---

h2d/Text.hx
samples/Text.hx

Text.getSize().y is now always 0. Should be the same with .x, but this currently causes problems with Flows when text alignment is not Left.

Text.getSize().y always 0

---

h2d/RenderContext.hx
h2d/SpriteBatch.hx
h2d/TileGroup.hx
h3d/Engine.hx

- Removed allocations in h2d.RenderContext.pushTarget()
- Re-use `h3d.Buffer` in SpriteBatch (disposed only when the buffer is too small)
- Fixed `h3d.Buffer` creation in TileGroup (when empty)
- Fixed `Null<Int>` alloc for optional args in Engine.setRenderZone()

Allocation optimizations

---

hxd/Pad.hx

On SDL, a pad can be initialized twice (gctrlCount / GControllerAdded event).
The first initialized pad was never correctly closed.

Fixed SDL pad double init

---

h2d/Graphics.hx

When the radius is negative, the drawCircle function will end up drawing a triangle instead of a circle.
Before:
After:

Prevent drawCircle from drawing a triangle when the radius is negative

---

.travis.yml

There is `-lib heaps` in all.hxml, so we need to `haxelib dev heaps .` in order to use the current code base instead of using the released version.
There is some other issue with all.hxml, but I will leave it to you to fix. (`hxsl/UniqueChecker.hx:14: characters 17-31 : You cannot access the sys package while targeting js (for sys.FileSystem)`)

fix TravisCI setup

---

h3d/impl/MemoryManager.hx

The `Dynamic` flag was lost at this step.

Added Dynamic flag to ManagedBuffer

---

h3d/Engine.hx
h3d/impl/Driver.hx
h3d/mat/Texture.hx
hxd/System.hl.hx

- Uses `haxe.GraphicsDriver` as h3d driver implementation if `usesys` is defined (keep using GlDriver or DirectXDriver if usegl or hldx are defined)
- Always uses `haxe.System.emitEvents` if `usesys` is defined

Added more usesys

---

hxd/fs/BytesFileSystem.hx

Currently it determines the image encoding from the path name.
A better way is to inspect the bytes headers.

[js] Implements BytesFileEntry.loadBitmap

---

h2d/Font.hx

When resizing a font narrow chars like '1' or 'I' will become even more narrow. Seems to be an accumulative effect when doing several resize operations. 
By using the initial size of the font to calculate width ratio instead of current size the issue is solved.

Narrow chars becoming more narrow when resizing font

---

hxd/fmt/fbx/Parser.hx

Hi @ncannasse,
I'm trying to import some [Kenney assets](https://kenney.nl/assets/castle-kit), and it was throwing from Parser.hx:
```
/home/jward/tools/haxelib/heaps/1,2,0/hxd/fs/Convert.hx:47: characters 83-88 : Unexpected ',' (} expected) (line 279) in /home/jward/dev/heaps-project/res/Models/towerSquareBaseColor.fbx
```
Looking in his .fbx files, many (all?) have Materials a nodes with **trailing commas**. Here's a screenshot, I included the header with file format info:
Again, I'm not sure if this is right or will have other consequences. But after this fix, heaps began converting these assets correctly:

Allow trailing comma in after a-node

---

h3d/pass/Blur.hx

In h3d/pass/Blur.hx, if the third parameter (output) of the function apply is not null, every pass would be applied to the src texture, which is not modified : as a result, even if we ask for 5 passes, we'd get the same result as with 1 pass only.
Copying src to output before the loop (should we check for sizes ?) and applying to output should do the trick.

Bugfix in h3d.pass.Blur

---

samples/templates/.vscode/tasks.json

I think it's good practice to omit these, even if VSCode generates them automatically. If done so, the defaults from vshaxe's task generation will be used, which means it's more future proof if the list of problem matchers there ever changes. It also makes for a more consise task definition.

Avoid redundant problemMatcher list in tasks.json

---

h3d/impl/GlDriver.hx

Only Chrome returns ES version in the optional vendor specific section of the string returned by pname "VERSION". Firefox only returns the webgl version, so this uses the version returned by SHADING_LANGUAGE_VERSION, which should work for all browsers.

fix setting glES version in firefox

---

hxd/res/FontBuilder.hx

Using ttf fonts, many of the fonts we use get rendered weirdly with neighbouring chars bleeding over. 
Seems like height sometimes is not picked up properly, and some width margin is needed to ensure glyphs are intact.
We are running with this modification on 9 games with 8 languages and 5 different fonts, and have not seen any issues on any devices after applying this fix.

JS text rendering glitch

---

hxd/fmt/fbx/BaseLibrary.hx
hxd/fmt/fbx/Parser.hx
hxd/fmt/hmd/Dump.hx
hxd/fs/Convert.hx

Expands FBX parser capabilities to work with binary FBX files.  
There are limitation on properties, which are:
* Int64 properties stored as Floats.
* Raw binary data property read as String.
Both are due to lack of corresponding FbxProp enums.
Information on parsing was based on this article: https://code.blender.org/2013/08/fbx-binary-file-format-specification/

[WIP] Implement binary FBX support

---

hxd/fmt/fbx/Parser.hx

Or so I thought it will take a rework. In reality 3 fields just became Int64 instead of Int32. This PR does not really introduces proper 7500 FBX support, because I read only low 32 bits, and discard high 32, meaning that files larger than ~2GB cannot be parsed. What a loss :)
I need more FBX7500 files to test thought, because while I managed to parse file posted in #403 [here](https://github.com/HeapsIO/heaps/pull/403#issuecomment-410761180), I could not get it to render (actually even blender couldn't load it).

Binary FBX 7.5+ support

---

h2d/filter/Blur.hx
h3d/pass/Blur.hx

Seems like argument order is incorrect when h2d.filter.Blur calls h3d.pass.Blur

Fix blur filter argument order

---

h2d/filter/Group.hx

When using multiple filters extending bounds, such as Glow, edges of the filter will be trimmed off. 
Issue seems to be that group boundsExtend are calculated as a max value, but in actuality the bounds will add up.

Filters cut off when using grouped filters with boundsExtend

---

hxsl/GlslOut.hx

Getting an error with heaps on IE since reported ES version is 0.94, so '#version' in shader is set to 94. However IE expects it to be 100.

Fix issue with gl shader version being < 100 on IE

---

hxd/Stage.js.hx

It's debatable whether you want to _always_ prevent scroll events... But 1) it looks like [touch event defaults are prevented by default](https://github.com/HeapsIO/heaps/blob/master/hxd/Stage.js.hx#L201), and 2) this makes sense for a game engine... so I think preventing wheel events is a good default also. Otherwise, wheel events interact with both the app and the page, which is almost always undesirable -- e.g. try to wheel-zoom in the [world demo](https://heapsio.github.io/heaps.io/samples/world.html):

preventDefault() on wheel events -- keeps page from scrolling

---

h2d/CdbLevel.hx

It's easier to get tile groups properties from CdbLevel than to parse them manually afterwards

Save tile groups for tilesets

---

hxd/snd/Manager.hx
hxd/snd/openal/Driver.hx

Poor audio quality on JS was caused by resampling of F32 data to I16, resulting in extreme precision loss.
It's a partial fix of #431, but response time and early cut issues still present.

Fix audio quality issues on JS target

---

hxd/snd/NativeChannel.hx

Adds pooling of created ScriptProcessorNodes, to avoid memory leaks. As in chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=379753
Reported by @lbergman here: https://github.com/HeapsIO/heaps/issues/431#issuecomment-425915172

Add workaround to chromium memory leak for js audio.

---

hxd/net/BinaryLoader.hx

Modern standard uses `loaded` and `total` variables instead of `position` / `totalSize`. Fixed `BinaryLoader` to use proper variable names, but kept the compatibility with older ones. 
Btw does it even have to keep comparability? Old variable names are quite outdated and Heaps utilizes pretty modern APIs in general.

Update variable names for XHR progress event with compat.

---

hxd/snd/NativeChannel.hx
hxd/snd/openal/Emulator.hx

Okay, this is quite large internal change. Primary reason to such drastic change - poor browser support of ScriptProcessorNode. (Memory leaks, asynchronous method of operation, latency, etc. Also it's deprecated in favor of AudioWorklets).
Current approach pretty much uses same method as ScriptProcessorNode, but instead relies on `AudioBuffer` and `AudioBufferSource` for playback, which are a lot more stable.
Implementation notes:
* `time` variable is mandatory to sync back-to-back buffer playback, otherwise they will have an audible gaps due to `ended` event being asynchronous, and `AudioContext.currentTime` being slightly ahead in time.
* It always fills both buffers at start (bufferSamples*2), I'm not sure how that'll work out for extremely short sounds that fit in just one buffer.
* …

Rework JS NativeChannel

---

h3d/scene/CameraController.hx

By slightly adjusting the limiter on `targetPos.z` gimbal lock is resolved. This does decrease the vertical camera flexibility, but only by `0.00001999` :)
Fix #340

Fix camera gimbal lock

---

h2d/Text.hx

`rebuild()` checks if Text was added to Scene properly, which prevents it from initializing glyph data, and, in turn, disabled ability to render text onto texture without adding it to into scene chain.  Fix now checks for `calcDone` on draw call and initializes glyphs if it wasn't done yet.
Fix #358

Text: Initialize glyphs if they weren't on draw call.

---

h2d/Particles.hx

Feature requested in [this topic](https://community.heaps.io/t/make-particles-position-not-relative-to-its-parent/39).
Adds support to make particles non-relative.
Implementation details:
I apply position difference between initial global position of particle and new global position of particles objects. Calculations are done once per particle init and once per frame per group (multiple particle groups would invoke `Object.localToGlobal` multiple times and initialization of object would call it `nparts` time per group).
There also an issue with some particles "twitching" while in this mode, most likely due to conversion local->global->local->global and I'm not sure if I'll be able to solve this issue.

Add support for non-relative 2D particles

---

h2d/Video.hx
h3d/impl/GlDriver.hx
samples/Video.hx

Provides basic implementation of h2d.Video on JS target.
Tested on WebGL2 compatible browsers and abomination that shouldn't have seen light of day - Edge (WebGL1).
What's lacking:
* ~Video is set on loop, it never actually invokes `onEnd`~
* Video should be provided as an url and cannot be bundled as part of embedded or pak resources.
* ~There is no error handling (e.g. if video loading fails)~
* Adds out-of-spec function to `GlDriver` on JS target to allow rendering of the video element onto texture.
* No audio output provided.
Overall this implementation feels a bit hacky for me personally, so I'd be glad to receive some feedback. Especially if some of the provided above points should be fixed before merge. 
Fix #444

Basic video support on JS target.

---

h2d/Interactive.hx
h2d/Scene.hx
h2d/col/BitmapCollider.hx
h2d/col/Circle.hx
h2d/col/Collider.hx
h2d/col/PixelsCollider.hx
h2d/col/Polygon.hx
h2d/col/PolygonCollider.hx
h2d/col/Polygons.hx
h2d/col/RoundRect.hx
h2d/col/Triangle.hx
samples/Interactive2D.hx

Basically allows for refined hit-test on mouse for `h2d.Interactive` with usage of `h2d.col`. With a sample.
What I don't like: It's still limited to width/height parameters. But removing them would make it a breaking change. Solutions are:
* If shape is present, ignore width/height and use shape bounds.
* Remove those outright and just have the shape as input, same as `h3d.Interactive`. + introduce Rectangle shape.
* Or just merge it as is, because it just works already, but is a pain to use, because you have to sync shape position and width/height manually, otherwise some parts of shape won't be checked for collision.
Also not sure if it need the `preciseShape` or not.

Add `shape` support to `h2d.Interactive`

---

hxd/fmt/fbx/BaseLibrary.hx
hxd/fmt/fbx/HMDOut.hx

For some reason FBX->HMD converter tried to read only one animation from FBX. This change forces it to save all animation stacks present in the FBX.

FBX: Save all animations to HMD.

---

hxd/fmt/fbx/Data.hx
hxd/fmt/fbx/Parser.hx

Bug was caused due to JS specifics and `readString` tried to read it into cohesive valid String. I disabled handling of `R` property type (Raw binary data) - it isn't used anywhere where it maters. Right now it resolves to empty `PString`. If someone will need to parse those properties for some reason - better file an issue. (It will require adding new enum - PBinary, and subsequent handling of it in all places where this enum is checked)
Fixes #456

Fix runtime JS parsing crash on invalid codepoint on Raw binary property

---

h2d/Interactive.hx
h2d/Scene.hx

* Ignore width/height if `shape` is set.
* Add invDet cache to h2d.Interactive
* Simplify `eventToLocal`
* Disable `isEllipse` for shapes.
* Some documentation.
* Visibility check was relocated before collision check.

Improve h2d.Interactive collision with shape.

---

hxd/fs/Convert.hx
hxd/fs/LocalFileSystem.hx

Right now, there's basically no robust way to add Convert to the FileSystem to be executed at compile-time. This PR aims to introduce robust and easy to understand way to do so.
I used same approach as with `hxd.res.Config.extensions` - as in, provide the Convert class.

Robust interface to add Converts.

---

h2d/Text.hx

My initial fix didn't do the proper job.
First, it didn't check for existence of text and font in the first place. Second, it did not use rebuild, which resulted in newly-created Text not populating glyphs.

Fix Text rendering on texture.

---

h2d/Interactive.hx
h3d/scene/Interactive.hx

* Added documentation to `onPush`, `onRelease`, `onReleaseOutside`, `onClick`, `onOver` and `onOut`
* Removed usage of `ERelease` kind during `onRelease` when event is `EReleaseOutside`
* Add `onReleaseOutside` event that fires instead of `onClick` if released outside Interactive hitbox area.
Personal remark: Due to lack of documentation it was unclear how `onRelease` worked, and the fact that it used `ERelease` while in reality event was `EReleaseOutside` didn't help a lot. 
Close #502

Improve Interactive (both h2d/h3d)

---

hxd/res/FontBuilder.hx

Chrome with their latest [update](https://chromium.googlesource.com/chromium/src/+log/339739f679a9ad4943d77add01513b409f60f416/third_party/blink/renderer/core/html/canvas/text_metrics.cc) adjusted text metric for their baseline value to more correspond to the standard (something only FF has done previously). This however results in varying results across browsers since `top` baseline is calculated differently between browsers. `bottom` however seems to be more even across all browsers (compare this [fiddle](http://jsfiddle.net/j87bY/1/) in FF and Edge/Safari for example). Due to this I suggest using `bottom` as baseline instead.
I've also removed the previously added arbritrary `xMarg` value which was added to prevent artifacts/scrambled chars. Using `bottom` textBaseline seems to prevent …

textBaseline bottom for js target in font builder for more even result across browsers

---

hxsl/AgalOut.hx
hxsl/Flatten.hx

This operation is required for new SDF-fonts to work in flash/AIR target.

added Smoothstep AGAL operation

---

h3d/impl/DirectXDriver.hx
h3d/impl/Driver.hx
h3d/impl/GlDriver.hx
h3d/mat/Texture.hx

- Adds `Driver.captureSubPixels` function with `bounds:h2d.col.IBounds` argument that allows to capture only region of the texture. Implemented on GL and DX drivers.
- Adds optional bounds argument to `Texture.capturePixels`.
Reasoning:
Sometimes you don't need entire texture pixel data captured, but only specific region of it. This provides robust API to do so.

Add captureSubPixels

---

hxd/fmt/bfnt/FontParser.hx

Happens if there's no trailing spaces and used CRLF line endings.

Fix BFont text format not parsing last value

---

h2d/HtmlText.hx

* Fix `<font face` causing rebuild recursion due to `buildSizes` assigning font, which caused `rebuild` which caused `buildSizes` assigning font, which caused `rebuild`, which caused...
* Fix SDF font rendering as non-main font. If SDF font was assigned via `<font face`, it did not had an SDF shader assigned, rendering raw SDF texture instead of proper glyph. 
Personal remark: HtmlText is a mess in general. Having different size fonts breaks word-wrap, vertical spacing, alignment, etc. And adding `<p align` support in current implementation is not as trivial as just always calculating lines.

Fixes to `h2d.HtmlText`

---

hxd/SceneEvents.hx

Why nobody noticed it before? Especially given the fact that docs specify `onCancel` being called on `stopDrag` (in `h2d.Scene`). 
👍

Actually call `onCancel` during `stopDrag`

---

hxd/res/FontBuilder.hx

Noticed that in some scenarios there will be artifacts, as described in https://github.com/HeapsIO/heaps/pull/390
With https://github.com/HeapsIO/heaps/pull/505 that issue seemed to be gone in our tests, but now we found a case where it shows up again, but adding back the safety margin solves the issue.

Reintroduce font build safety margin to avoid rendering artifacts

---

h2d/Interactive.hx
h2d/Layers.hx
h2d/Mask.hx
h2d/Object.hx

* Added `Object.onOrderChanged` called when changing object ordering in `h2d.Layers`.
* Fixed `h2d.Interactive` not updating it's interaction order when using `over`, `under` or `ysort`.
* Added more features to Layers
* `getChildLayer` - returns layer on which specified child resides.
* `getChildLayerIndex` - returns index of a child relative to it's layer.
* `addAt` - adds child to specific layer and index of that layer. Useful for people who use `Object.addChildAt` and want to utilize adding at index with Layers.
* `moveChild` - moves Object within layer. Allows for more refined reordering within layer boundaries compared to `over`/`under`.
* Added documentation to functions.
Fixes issue described here: https://community.heaps.io/t/interactives-overlap-layers/160
Edit: Build fails due …

Fix/improve h2d.Layers

---

hxd/res/Config.hx
hxd/res/Sound.hx
hxd/snd/Mp3Data.hx

Depends on HaxeFoundation/hashlink#214
Allow playback of mp3 files on Hashlink, allowing usage of mp3 as multi-target sound format.

Add MP3 support to Hashlink.

---

hxd/UString.hx

On non-ASCII symbols it returns correct result now

Fix UString length result

---

hxd/res/Sound.hx
hxd/snd/Channel.hx
hxd/snd/Manager.hx

* Sound now support `LIVE_UPDATE`.
* `hxd.snd.Manager` now have `getAll( sound : hxd.res.Sound )` which would return iterator of all currently active channels of specified Sound.
* Added safeguard to `Channel.position` to avoid out-of-bounds position and undefined behavior when trying to buffer sound data. Should it wrap around if `loop == true`?

Add liveupdate support to Sound

---

h3d/parts/GpuParticles.hx

During development with GpuParticles we realized addGroup() didn't accept custom material passed and this was needed for having Additive blending.

Making sure input material is set

---

h2d/Interactive.hx
h3d/scene/Interactive.hx
hxd/SceneEvents.hx

* `currentOver` was replaced by `overList`
* `EOut` events no longer reset `mouseDownButton`, as it prevents firing of `onReleaseOutside`.
* `Interactive` interface expanded to expose `cursor` and `propagateEvents`. Used to properly set cursor when over list changes and do propagation checks.
resolve #209

Implement multiple Overs for Interactives

---

hxd/Pad.hx
samples/Pad.hx

Added configs to fix analog sticks (also A/B/X button layout on Firefox)
For some reason, Firefox doesn't see D-Pad, so its not usable there
Although it doesn't break any old code, it requires using `pad.config` to get button code rather than  `hxd.Pad.DEFAULT_CONFIG`

Add Dualshock 4 config for JS

---

h3d/parts/GpuParticles.hx
h3d/prim/Primitive.hx
h3d/scene/CustomObject.hx
h3d/scene/Mesh.hx
h3d/scene/MeshBatch.hx
h3d/scene/Object.hx
h3d/scene/Scene.hx
h3d/scene/World.hx
h3d/scene/pbr/terrain/Tile.hx
hxd/App.hx
hxd/fmt/hmd/Library.hx

Resolves #336 
What I'm not sure about is `dispose` calls. Currently it call dispose on primitive only if it's the only reference to the Mesh.
Adds `refCount:Int` variable, `incref()` and `decref()` methods. Later will dispose of the primitive if refcount reaches 0.
GpuParticles will increase refcounter during serialization to avoid unintentional disposing of it.
HMD models are not disposed due to Library increasing refcounter.

Implement reference counter on primitives

---

hxd/SceneEvents.hx
hxd/System.hx

Also docs for System.setNativeCursor to clarify it's usage.
Partially resolves #582 
Should there be wiki doc to clarify how to utilize cursor system? 
In general, I thinking about making separate "Community notes" section that will be much more chaotic (code snippets, samples, gists, etc, as name suggests - notes) and faster to produce and not a detailed thought-out doc pages, but they would cover some things community seem to have difficulties with. Lack of documentation is biggest issue people have, and not a lot of people willing to spend a lot of time (including me) to write proper documentation.

Add SceneEvents.defaultCursor

---

hxd/BitmapData.hx

From the Mozilla documentation:
```
void ctx.drawImage(image, dx, dy);
void ctx.drawImage(image, dx, dy, dWidth, dHeight);
void ctx.drawImage(image, sx, sy, sWidth, sHeight, dx, dy, dWidth, dHeight);
```
When only x, y arguments are used, they are taken as destination x,y, not source x,y like they should, resulting in black image.
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage

fix for Bitmapdata.sub() on javascript

---

hxsl/Ast.hx
hxsl/Checker.hx
hxsl/Dce.hx
hxsl/GlslOut.hx
hxsl/HlslOut.hx

Adds `fetch` and `fetchLod` functions to `Sampler2D` and `Sampler2DArray` allowing for non-UV-based texture pixel fetching.
Additionally fixed ivec and bvec generation both for GLSL and HXSL.
I'm not sure what to do with GLES2. Throw an error saying that `texelFetch` is not available on GLES2? Emulation will require adding size uniform for each texture and I'm not sure how to implement such thing (assignment of texture also assign _size uniform. I personally would like to have at least emulated support for GLES2, as not all browsers support GLES3. 
I did not implement if for flash, because I have no clue how it works and does it even support such operation.
Resolves #549

Implement GLES3+ and HXSL texelFetch

---

README.md

I didn't realize there were channel-specific invite links before, so I used a more generic one for the badge when I added it (instead of the one from further down in the readme).

Use proper Discord invite link

---

hxd/App.hx

Fix vscode `override` completion generating `onLoaded:() -> ?` (which is invalid syntax caused by plugin/completion server not being sure what that function returns).
Also newline because Github build-in editor is "smart". :)

Add type to App.loadAssets onLoaded argument

---

h2d/RenderContext.hx
h2d/Scene.hx
samples/ScaleMode2D.hx

* Closes #524, closes #563.
* Implements 8 different scaling modes for `s2d.Scene`.
* Deprecates `zoom`. Now can be done with `ScaleMode.Zoom(v)`
* Deprecates `setFixedSize`. Now can be done with `ScaleMode.Stretch(w, h)`.
* Removes size checks each frame and instead hooks to window resize events.
Now onto modes:
* `Fill` - it's the default and just resizes Scene to fill engine size.
* `Stretch` - basically good old ugly `setFixedSize`.
* `KeepAspect` - scales Scene with preservation of aspect-ratio. Can anchor on top-left and center.
* `KeepPixelSize` - same as above, but uses integer scaling to ensure square pixels.
* `Exact` - just forces width/height/zoom/centering disregarding adaptation.
* `Zoom` - Same as old `zoom` variable.
* `EnsureArea` - works same as KeepAspect, but instead …

Implement 2D Scene ScaleMode

---

h3d/impl/GlDriver.hx

HaxeFoundation/Haxe#8422 changed that TypedArrays are no longer compatible with each other directly via `interface`, so there is now a need for implicit declaration that it is indeed an ArrayBufferView. Fixes JS compilation/completion server being unhappy.
P.S. Trusting compiler in figuring out variable type is not always the best decision. ;)

Fix JS target after HaxeFoundation/Haxe#8422

---

h2d/Camera.hx
samples/Camera2D.hx

Bugfix in h2d/Camera, correcting calculation of viewX and viewY in set_viewX(), set_viewY() and in sync().
Also extend the sample class Camera2D to correctly visualize
camera parameters and the camera anchor point in screen and scene space.
Please see this issue #647 to get further information about the changes.

Bugfix in h2d/Camera, correcting calculation of viewX and viewY

---

h2d/domkit/Style.hx
samples/Domkit.hx

I was trying to get started on heaps + domkit but the demo wouldn't work.
I had to do [domkit#9](https://github.com/HeapsIO/domkit/pull/9) too to make it work.
Note: I was using heaps `7a216be` and domkit `195fa25` (both latest at the time)
I'm not sure about `#if (sys || nodejs)`, maybe it should be handled differently?

Fix domkit (v2?) demo for js

---

hxd/Key.hx

Related: #671 
Wheel events are special case, because they only have "on" signal, and never "unpressed", sometimes confusing people when they use `Key.isDown` with them and end up with `true` each frame after first scroll.
Added documentation clarifying that wheel should only be checked via `isPressed` as well as note the shortcomings of this approach with appropriate alternatives.

Add docs to `Key.MOUSE_WHEEL_*` variables

---

h2d/Interactive.hx
h3d/scene/Interactive.hx
hxd/SceneEvents.hx

Resolve #675; Resolve #566
* Ensure EOver is called after EOut
* Remove ability to cancel EOver/EOut
* Update docs for onOver/onOut
For backward compatibility - rel values of Event are retained in case they used during EOver. I'm not sure if `relZ` should be retained. I have a feeling that docs are a bit lacking still in clarifying of EOver/EOut special case.

Reorder EOut/EOver events

---

h2d/col/IPoint.hx
h2d/col/Point.hx
h3d/col/IPoint.hx
h3d/col/Point.hx

I propose adding `equals` methods to the `Point` classes. 
The only one missing is `h3d.col.FPoint` which didn't work on `Windows - HL 1.10` (I didn't test other targets), I suppose that's due to float precision shenanigans.

Add `equals` to `Point` classes

---

hxd/System.js.hx

Added basic device detection based on user-agent. Enables support for IsTouch & IsMobile detections on JS target.
Not perfect detection, but it works for most platforms, and there's no better solution without relying on external libs.

Js touch detection

---

hxd/snd/Manager.hx
hxd/snd/NativeChannel.hx
hxd/snd/openal/AudioTypes.hx
hxd/snd/openal/Driver.hx
hxd/snd/openal/Emulator.hx
samples/Sound.hx

* Added initialization for `sampleOffset` to avoid `getPlayedSampleCount` returning NaN.
* Implemented support for master volume on JS and made volume control immediate instead of applied on next buffer.
* Fixed crash with stb_ogg_sound resampling due to incorrect sample count calculation (allows to play ogg files that aren't 48k).

Audio fixes part 2: JS

---

hxd/App.hx

That one was a thorn in my side for half a year already.
When setting 2D scene via `App.setScene`, it screwed up the event ordering, causing it to receive events after s3d.

Fix event ordering when setting s2d via App.setScene

---

hxd/impl/TypedArray.hx
hxd/snd/Driver.hx
hxd/snd/Manager.hx
hxd/snd/Mp3Data.hx
hxd/snd/NativeChannel.hx
hxd/snd/openal/Emulator.hx
hxd/snd/webaudio/AudioTypes.hx
hxd/snd/webaudio/Context.hx
hxd/snd/webaudio/Driver.hx
hxd/snd/webaudio/LowPassDriver.hx
hxd/snd/webaudio/PitchDriver.hx
samples/Sound.hx

* Implements new default audio driver for JS target that works directly with WebAudio
* Can be disabled with `-D useal` flag, then legacy AL emulation is used.
* Changed audio context unlock to not eat up user input.
* Both AL emulator and WebAudio context use shared `hxd.snd.webaudio.Context` as audio provider to avoid code duplication.
* Implemented experimental pitch, low-pass and spatialization effects. (See notes below)
* Disabled resampling to native frequency for WebAudio driver, since it supports automatic resampling under the hood.
* LowPass won't produce same sound as with HL/AL, but at least it's working.
* Spatialization uses built-in Panner/Listener combo, meaning that velocity is not supported.
* Pitch is a tough nut, because of Absolutely Sane And Not Idiotic WebAudio …

Audio fixes part 3: WebAudio driver

---

h2d/Drawable.hx
h2d/Object.hx
h2d/RenderContext.hx

* `Drawable.color` affects only object itself and not the filter.
* `Object.alpha` affects transparency of both object and filter.
* `Drawable.color.a` can be used to manipulate object transparency while inside filter.
Change probably should be tested internally in case it borks stuff in Northgard or something ;)
Fixes #670

Make Drawable.color to not affect the filter

---

hxd/System.hl.hx
hxd/Window.hl.hx

https://github.com/HeapsIO/heaps/issues/715
Would be nice to have an option of a fixed window size. I added windowFixed macro to change DX and SDL window create flags to remove the resizable flag. I tried to keep its setup as the same as windowTitle/windowSize. 
This could also be done by adding the define on the Hashlink side, but I was trying to match the current window define macros.
Issue https://github.com/HeapsIO/heaps/issues/417 was closed but I couldn't find how you could possibly change the window creation params to disable window resizing without editing heaps or hashlink.

Added windowFixed macro to disable window resizing.

---

h3d/mat/Texture.hx

preventAutoDispose() is used to set a "big" timeout preventing MemoryManagers and such to dispose textures. But this doesn't work when for example GLDriver overwrites lastFrame.
This fix makes sure that external writes to lastFrame wont overwrite a texture with preventAutoDispose set.

fix: prevent textures with preventAutoDispose to be disposed

---

hxd/fs/Convert.hx
hxd/fs/FileConverter.hx

Adds `version` variable to `Convert`. Allows invalidation of .tmp cache without user involvement when new version is introduced.
Also added `disable_res_cache` define, which ensures that cache is always treated as invalid. Intended use is for people who write their own converts to ease up the development process.
Ref #720

Add version for converts

---

h3d/shader/AlphaMap.hx

For some reason, alphaMap used Blue channel instead of Alpha as source 🤔

Fixed AlphaMap shader (incorrect channel)

---

h2d/Scene.hx

Fixes pixel bleeding with some window sizes when using scaleMode with center alignment.
Before:
After:

Fix pixel bleeding with center scaleMode align

---

h2d/Mask.hx
samples/Mask.hx

* Adds `scrollX` and `scrollY` to Mask, allowing to scroll the contents.
* Adds wrappers `scrollTo` and `scrollBy` as shortcuts.
* Updates Mask sample to showcase scroll feature.
Ref #606; (Does not resolve actual issue, but related)

Implement Mask.scroll

---

hxd/Charset.hx

Fixes invalid word-wrap on CJK characters, as unicode CJK table is far bigger than the range that was checked.
Implementation based off Unicode ID class specification: https://www.unicode.org/reports/tr14/tr14-34.html#ID
Implementation includes accurate CJK detection following ranges given by spec precisely and less accurate (default) check that provides less accuracy, does not include a few ranges, but uses far less checks. Accurate detection can be enabled with `accurate_cjk_detection` flag.
Ref https://github.com/HeapsIO/heaps/pull/553#issuecomment-572340982 for examples of text where incomplete CJK detection causes lack of word-wrap.

Implement better CJK detection

---

h2d/Object.hx

While working on DKH we encountered a bug.
If an object with a filter is offscreen the RenderContext keep pushing the filter without ever poping it, resulting in a weird behavior and a leak.

Fix incorrect pop filter on offscreen object

---

h2d/HtmlText.hx

* Fixes crash on empty text nodes. Was caused by the fact that line was marked as a line that contains content, while it actually doesn't. 
* Fixes `getTextProgress` on HtmlText. Bug was in initial implementation and happened because `text` was changed, and `progress -= text.length` in case if `text.length == 0` caused `progress` to never reach 0.

HtmlText fixes

---

hxd/File.hx

For some obscure reason, the method used to upload a file to an app on Chrome didn't work sometimes (the Open window would pop-up, but the onChange callback wasn't called).
The new version adds the <input> element to the actual <body> and it stays there, hidden.

Fixed JS version of hxd.File.browse on Chrome

---

h2d/Interactive.hx
h3d/scene/Interactive.hx

The Interactive.cursor is nullable, as it's actually supported in the SceneEvents.selectCursor . A nice hidden but useful feature ;)

Marked Interactive.cursor as nullable

---

hxd/fs/FileConverter.hx

Basic implementation of adding converts without need to introduce props.json to the project. 
Introduces `hxd.fs.FileConverter.addConfig` which takes structure compatible with props.json and doc with sample of usage.
In my case, I use it for gif -> spritesheet + frame data conversion:
```haxe
// in GifImage resource class, since registering those in Convert class requires manually
// causing that class to resolve statics at some point.
static var _ = hxd.fs.Convert.register(new hxd.heeps.GifConvert());
static var __ = hxd.fs.FileConverter.addConfig({
"fs.convert": {
"gif": "giff"
}
});
```
Ref: #743 (close if satisfied with such implementation, or leave if can be improved later)

Add ability to enable converts without props.json

---

h3d/prim/Cylinder.hx
h3d/prim/Disc.hx

Add methods to Cylinder and Disc to get a default unit to be api consistent with Cube and Sphere.

Feat: Add defaultUnit methods to Cylinder and Disc

---

h2d/RenderContext.hx

Allows to use AnimatedTexture, UVAnim and UVScroll shaders in 2D context, since they rely on `global.time`.
Alternative solution is to change `time` to `global.time` and change shaders that use it, but it's a clear breaking change and I'm not sure if other people rely on 2D time global.

Add global.time to 2D shader globals

---

h2d/Flow.hx
h2d/Mask.hx
h2d/RenderContext.hx
h2d/TextInput.hx
samples/Flows.hx
samples/Mask.hx

Ref: #606 
* Implemented `Mask.maskWith` and `Mask.unmask` methods. 
Had to use static stack to hold renderZone state, otherwise using that API would break mask-in-mask (and most likely filters). Alternatively I would say it's possible to change `setRenderZone` to `pushRenderZone(x, y, w, h, inherit)` stack, allowing for more robust render-zone handling. (With inherit = true, new renderZone would be clipped by existing renderZone)
* Changed `h2d.Flow.overflow` to an enum
* Implemented Hidden overflow.
* Added showcase of advanced masking to Mask sample.
I'm not touching `FlowOverflow.Scroll`, too much have to be accounted, I'll leave it to the person who actually assigned to the task. ;)

Mask.maskWith API / h2d.Flow.overflow enum

---

hxd/System.hl.hx

Consider the following incorrect program using heaps:
```haxe
class Main extends hxd.App {
static var b : Array<Int>;
static public function main():Void {
//b = new Array<Int>();
b.push(42);
}
}
```
That program tries to add element to an array that wasn't allocated, which is obviously incorrect. Compiling and running under Linux causes the program to hang in an infinite loop:
```
$ haxe -main Main -lib heaps -cp . -hl foo.hl
$ hl foo.hl
Null access
Called from $Main.main (Main.hx line 6)
```
The problem is in the [System.reportError](https://github.com/HeapsIO/heaps/blob/2b3efb27a55dd17901d3be47b146011d6bf763d8/hxd/System.hl.hx#L155) function that attempts to display a stacktrace in a window. However, UI subsystem is not implemented in hashlink on Linux ([see …

Only display stacktraces in a window on Windows platform

---

hxd/Window.hl.hx

https://wiki.libsdl.org/SDL_TouchFingerEvent
N.B. : Since we're rounding the normalized value using 100 factor, we can have an 1% windowWidth pixel loss (`792px` vs `799px` for `800px` default windowWidth), maybe we should increase the factor by 10 there and here, what do you think @ncannasse ?
https://github.com/HaxeFoundation/hashlink/blob/a30209ef5020fce4b3b1cda3e7a4fed2edd7f118/libs/sdl/sdl.c#L186-L203

fix: handle normalized SDL touch coordinates

---

h2d/HtmlText.hx
h2d/Text.hx
h2d/domkit/BaseComponents.hx
hxd/fmt/bfnt/FontParser.hx
hxd/fs/Convert.hx

* Defaults `Text.letterSpacing` to 0
* Invalidates all bitmap fonts (since we can't detect which one is affected)
* Revert weird hotfix from 2014.
* Added `HtmlText.imageSpacing` (defaults to 1)
There was one particular part I missed when pitching the change. HtmlText uses letterSpacing to pad `<img>` tiles. Hence - introduced `HtmlText.imageSpacing` which remains defaulted to 1.
Closes #720

Default letterSpacing to 0

---

h2d/RenderContext.hx

This is a method to push a new render zone to the h2d RenderContext, but it first clips (intersection) to the current render zone so that the current zone is still respected. I use this for rendering child objects in a UI hierarchy so that children cannot render outside their parent (all the way up the tree).

Add h2d.RenderContext.clipRenderZone

---

hxd/res/FileTree.hx

Gate out `hxd.res.FileTree` in `macro` in order to fix haxe completion (e.g. explicitly showcase that this is macro context)

Fix FileTree completion in macro context

---

hxd/res/BDFFont.hx
hxd/res/Config.hx

Created new Resource type hxd.res.BDFFont that extends Resource.  Use it to load/parse a BDF font files to h2d.Font instance.
Example usage:
`var f = hxd.Res.My_BDF_font_file.toFont();`
`var tf = new h2d.Text(f);`
A BDF font file (format created by Adobe, possibly in the 1980s) is a self-contained text file that contains packed bit data with optional smoothing/alpha and does not have a separate PNG bitmap.
The BDFFont resource parses the BDF file and creates it's own glyph tile. It uses a basic but pretty effective packing algorithm to generate (almost) the smallest tile it can to save space.
FontForge is an example program that is able to generate BDF files. The benefit of BDF files is that the entire font is self-contained. A negative of the BDF format is that it does not have support …

BDF font support

---

h3d/impl/GlDriver.hx

The original code generated `if((typeof)(WebGLDebugUtils) != "undefined")` which doesn't run in a browser. This should generate `if((typeof WebGLDebugUtils) != "undefined")` which will.
I'm a haxe novice and am not sure if this is the correct fix, but it appears to work.

Fix javascript error in GlDriver

---

hxd/fmt/fbx/BaseLibrary.hx
hxd/fmt/fbx/Parser.hx

* Altered string parsing on binary FBX. Now it cuts off anything past `0` byte if it's present in a string. This is due to Blender inserting `\0\1AnimCurveNode` extra data to curve node names, clearly expecting it being cut away on parsing.
* Removed Blender downscale hack: It's no longer required, as it's possible to export with proper unit scale (see wiki notes).

Fix Blender exports

---

h3d/impl/GlDriver.hx

When creating a combined depth-stencil buffer using the heaps Depth24Stencil8, WebGL GL_DEPTH_STENCIL is passed for creating the buffer. 
Setting this buffer both in depth and stencil attachment will render errors on mobile devices running webgl1. 
This fix binds the combined buffer to the DEPTH_STENCIL_ATTACHMENT.
Since the only way to have stencil is using the Depth24Stencil8 format the setting of stencil the old way should never be reached but keeping for safety reasons and maybe future two separate buffers will actually be created.

Render To Texture with depth and stencil.

---

h3d/impl/GlDriver.hx

There was an extra `}` in GlDriver.hx.
Fixes issue #866, introduced in PR #863.

Remove extra } in GlDriver.hx, fixing compilation

---

hxd/fmt/pak/FileSystem.hx
hxd/fmt/tiff/Reader.hx

Couldn't generate API docs because TIFF refused to compile on JS, since not a sys target.
* Added `tell` method to `hxd.fmt.pak.FileSystem.FileInput`
* Added conditional import of either sys FileInput or pak FileInput depending on target.
This is probably not the best solution, but at least works as a substitute to not break the JS. Honestly, there needs to be a better way to make cross-platform seekable input...
Pls don't break JS ;)

Fix TIFF compilation on JS

---

h3d/Vector.hx

The new `h3d.Vector.transformed(...)` returned the original vector instead of the transformed one.

Fix h3d.Vector.transformed() not returning the transformed vector

---

hxsl/Ast.hx
hxsl/Checker.hx
hxsl/MacroParser.hx
hxsl/Macros.hx
hxsl/Printer.hx
hxsl/Serializer.hx

Adds support for `@doc` metadata in HXSL shaders. 
Primary aim is to enable documentation of the variables generated by macros.
Usage example (from Base2d):
```haxe
@doc("Discard pixels with alpha below 0.001")
@const var killAlpha : Bool;
```

Implement @doc meta for shaders

---

h2d/HtmlText.hx
h2d/domkit/Style.hx
h2d/filter/AbstractMask.hx
h3d/scene/Renderer.hx
hxd/fs/FileConverter.hx
hxd/impl/Api.hx
hxd/inspect/PropManager.hx
hxd/inspect/PropTools.hx
hxd/inspect/ScenePanel.hx
hxd/inspect/SceneProps.hx
hxd/res/DynamicText.hx
hxd/snd/LoadingData.hx

Added `hxd.impl.Api.is` which replaces `Std.is` calls due to it being deprecated in favor of `Std.isOfType`. Fixes deprecation warnings for upcoming Haxe 4.2 onwards.

Fix Std.is deprecation warnings

---

hxsl/Ast.hx
hxsl/Checker.hx
hxsl/Dce.hx
hxsl/GlslOut.hx
hxsl/HlslOut.hx

Added support for `sampler.size()` and `sampler.isize()` methods that return `vec` and `ivec` respectively with the texture dimensions. 
For Sampler2D and SamplerCube it's `vec2` and Sampler2DArray is `vec3` with Z being element count.
As with `fetch`, there is no support for GLES2.0, since I have no idea how to implement hidden uniform with texture size as a substitute.

HXSL: Added texture size method support

---

hxd/snd/Manager.hx

while queuing sound in channel onEnd

fix: prevent double sound queuing

---

hxd/fs/FileConverter.hx

Fixes bug when Convert was ran every time if Convert happened on already converted file due to Convert version mismatch, because db file never updated the version value.

Fix Convert version not being updated

---

hxsl/Ast.hx
hxsl/Checker.hx
hxsl/Linker.hx
hxsl/MacroParser.hx
hxsl/Printer.hx
hxsl/Serializer.hx

Implements `@borrow(path.to.Shader)` qualifier to variables.
This is essentially reverse of the `@shared` qualifier and intended only for advanced usage. (As pretty much everything HXSL, frankly.) Lets user-defined shaders to borrow uniforms from other shaders. Does not perform checks for that shader actually being attached and is completely on the conscience of the user to ensure shaders they borrow from are present. This a follow up to #912 as an alternative way to access foreign uniforms. 
<details>
<summary>Usage example</summary>
In this shader I already posted before I need to know the texture size of Base2d to perform custom sampling filter transition curve that is specifically made for pixel-art. And "just set texture to what you going to render beforehand" is not a solution. …

HXSL: Implement borrow qualifier

---

hxd/System.js.hx

Currently, the browser *Animation Frame* is requested without any limitation, causing heavy CPU usage even when nothing really happens.
This change gives control to the dev to set a custom FPS cap that will limit the main loop framerate (including animation requests). This is typically very useful to lower FPS while the app loses focus (but isn't minimized).

Added a FPS limit for JS browser loop to help reducing CPU usage

---

hxd/System.hl.hx

Hey ;)
Mutex at `haxe/MainLoop.hx:112` is still null because it is static and it is not yet initialized when `__init__` magic tries to get access to it.  So, moving `timeoutTick` loop to the static initializer in the same way as `updateCursor` loop was moved in a previous 4.2 fixes will do the trick.
Thank you.

Fix for 4.2.1

---

hxd/Timer.hx

This PR fixes the default `smoothing` value of `hxd.Timer`, which wasn't complying its own description: 
- 0.0 on Hashlink target
- 0.95 anywhere else

Fixed default Timer smoothing to comply with its description

---

hxd/res/Atlas.hx

When starting an animation at 1, the first element in the contents map's array will be null. If removed at the end of the page parsing loop, when adding subsequent element, the index offset won't be reduced. Thus resulting in the insertion of null in the array. With the example atlas below it would give this : `[{...}, null, {...}]`.
Moving the array shift at the end of the parsing solve this issue.
```
cards.png
size: 1024,1024
format: RGBA8888
filter: Nearest,Nearest
repeat: none
manon_commons
rotate: false
xy: 0, 0
size: 678, 1024
orig: 678, 1024
offset: 0, 0
index: 1
cards2.png
size: 1024,1024
format: RGBA8888
filter: Nearest,Nearest
repeat: none
manon_commons
rotate: false
xy: 0, 0
size: 678, 1024
orig: 678, 1024
offset: 0, 0
index: 2
```

Fix crash on atlas loading with anim starting at 1

---

h2d/Console.hx

When a Console instance is scaled, the input isn't properly positioned. 
This PR fixes just that.

Fixed h2d.Console input position when console is scaled

---

hxsl/GlslOut.hx

_First of all, thank you for this engine, it's been nice to work with it! :)_
Now, I've been experiencing weird distortion issues on some mobile phones when moving not too far away from the origin (~2000px). Examples:
Actual vs Expected:
Also a video:
https://user-images.githubusercontent.com/1260622/121310872-1be55a80-c904-11eb-8a10-c4b3a1bc7ea0.mp4
I've constructed a minimal example that you might be able to reproduce on your phone if you are lucky: [website](https://zommerfelds.github.io/heaps-cordova), [source](https://github.com/zommerfelds/heaps-cordova/blob/main/src/App.hx). The white lines start to have unstable width and the top octopus starts to wiggle ([bad recording example](https://user-images.githubusercontent.com/1260622/121325390-da5bac00-c911-11eb-9ebd-2b14b0833a99.mp4)). …

Use highp for GLSL vertex shader

---

hxd/Window.js.hx

resize listener is not used, binded later when scene engine ready.
Timer was too inconsistant and caused various bugs.

Remove useless listener and timer

---

hxd/Key.hx
hxd/Window.js.hx

Fix a bug where if the click or a keysuch as alt, ctrl or shift was hit in a 3d scene then released outside of it, the release event was not captured.
Causing to stay locked on a specific edit mode even though the key is released.

Fix release click/key outside of scene

---

h3d/col/Bounds.hx
h3d/col/Capsule.hx
h3d/col/Collider.hx
h3d/col/HeightMap.hx
h3d/col/ObjectCollider.hx
h3d/col/Polygon.hx
h3d/col/PolygonBuffer.hx
h3d/col/SkinCollider.hx
h3d/col/Sphere.hx
h3d/col/TransformCollider.hx
h3d/prim/Sphere.hx
h3d/scene/Interactive.hx
samples/Interactive.hx

This property displays an object that shows the collider (wireframe by default)
Also updated samples/Interactive to use this feature
When you activate this, the new sample looks like this:
If you need the debug objects' materials to be different (eg. not wireframe), override `Interactive.setupDebugMaterial` which is a static dynamic function.

Add `showDebug` property to 3D Interactives

---

h3d/scene/Skin.hx

Note that this does not support non uniform scaling
This fixes issues with interactives on scaled skins not triggering when the camera is too close to the object.
Fixes at least part of #596

Fix h3d.Scene.Skin.getBoundsRec not scaling correctly

---

h3d/scene/Skin.hx

Optimizes #974 to have one less alloc per `getBoundsRec()` call

fixup! Fix h3d.Scene.Skin.getBoundsRec not scaling correctly (#974)

---

h3d/col/SkinCollider.hx
h3d/scene/Interactive.hx

SkinCollider.makeDebugObj shows a box containing the whole collider,
and a box for each joint.
Note that these boxes are made using h3d.scene.Box, which is a
h3d.scene.Graphics, which means you cannot change its color through its
material, and there is no wireframe mainPass to disable.
This uses some code from techTests/SkinBounds

Implement makeDebugObj for SkinCollider

---

h3d/scene/CameraController.hx

Use variables `minDistance` and `maxDistance` to set the caps.
Scrolling beyond those values will move the camera instead of zooming.
Note that it is still possible to go beyond min/max distance by changing
the fov.
Here is an example on HeapsIO/Hide with `minDistance = 1`, note how scrolling does not slow down past a certain point.

Add zoom capping to h3d.scene.CameraController

---

h2d/Font.hx
h2d/HtmlText.hx
h2d/Text.hx
h3d/shader/SignedDistanceField.hx
hxd/res/BitmapFont.hx

* `SignedDistanceField` shader now have `autoSmoothing` flag that causes `smoothing` to be ignored and its value calculated based  on `fwidth(distance)`.
* `BitmapFont.toSdfFont` now defaults to auto-smoothing.
* `Text` now automatically enables `smooth` if it wasn't explicitly set when SDF font is used.
* `HtmlText` now uses `Text.smooth` for SDF fonts.
* Improve docs a bit.
In general this is aimed to simplify out-of-the-box SDF font usage. fwidth is not a cure-all solution but should do the trick in most cases and provide decent crispiness on fonts without fiddling with smoothing value too much. I have to note that it works a bit worse on small font scales (since sampler jumps over multiple texels).
This is a somewhat of a breaking change for people who use `toSdfFont` without …

Add automatic smoothing support for SDF

---

hxd/Window.js.hx

The contextmenu listener would cause short vibrations on mobile devices when long pressing.
It happened because the contextmenu listener was defaultPrevented. Checking if the right
mouse button was clicked fixes the issue.

Fix web target causing haptic feedback when long pressing

---

hxd/Window.js.hx

This should fix issues that #967 introduced for some people, causing canvas not being properly resized at startup.
Solution uses JS API that is not present in Haxe 4.2, i.e. `ResizeObserver` class, however it is supported by [pretty much everything](https://caniuse.com/?search=ResizeObserver), and it provides far more consistent resize callback specifically for canvas as we don't really need to know if window was resized - only canvas itself.
Update: It seems that it didn't completely fix the issue, do not merge yet, I need to investigate.

JS: Use ResizeObserver when possible

---

h2d/Object.hx
h2d/RenderContext.hx
h2d/filter/AbstractMask.hx
h2d/filter/Ambient.hx
h2d/filter/Mask.hx

Close #903 
Fixes Mask positioning when filter resolution is customized.
RenderContext is now aware of current filter render resolution, allowing usage of it for logic in filters such as Masks.
Introduces a breaking change for `AbstractMask` extending classes as they now require passing of render context to `getMaskTexture`

Fix filter resolution scale with Masks

---

hxd/Window.hl.hx

In a multi-screen setup, the default screen mode is chosen using the main display instead of the current display

Fixed a default screen mode issue in a multi-screen setup

---

hxd/fmt/pak/FileSystem.hx

This method is absolutely required when using PakFS within HTML5, because it doesn't have access to sys package and is not multithreaded by nature.
When used in multi-threaded environment (i.e. HL) it will be marked as deprecated unless a define of consent for potential self-inflicted leg-wound is added.

Restore hxd.fmt.pak.FileSystem.addPak

---

hxd/fs/FileEntry.hx

Fix breaking API change from ea6012ab891a703c42b6d9b4a7bafa76a9766703
That method is actually being used, for example to distinct unprocessed .gif and processed .gif -> .png spritesheet with frame metadata chunk:
https://github.com/Yanrishatum/heeps/blob/56153497b9f8b6928731065229be0540cbd55810/cherry/res/GifImage.hx#L30-L32
I know it's not on purpose, but pls stop breaking file system ;)

Restore hxd.fs.FileEntry.getSign

---

h3d/mat/PbrMaterial.hx

In PBRMaterial.hx, changed Std.is to Std.isOfType to get rid of the warning

Fixed std.is warning

---

hxsl/GlslOut.hx

The keyword `sample` causes a runtime error on shader creation on JS target ("sample: Illegal use of a reserved word"). The below edit to `h3d.shader.SinusDeform` will cause the error, and errors also occur with `ScreenShader`. The same shaders work fine on HL.
```haxe
// h3d.shader.SinusDeform
function fragment() {
var sample = sin(calculatedUV.y * frequency + time * speed) * amplitude;
calculatedUV.x += sample;
}
```
This change adds "sample" to the reserved keyword list.
Tested in Edge browser on heaps 96c2e91a072788e91aea7e3b5d4b5c82cbe57f3b

"sample" not allowed in JS shaders

---

hxd/fmt/pak/Build.hx

Even if it's similar to the `-exclude-path` arg, I think this one is easier & more versatile, as it's not dependent on a full path.
Usage: `-exclude-names backups,tmp,placeholders`

Added support for -exclude-names arg to PAK builder

---

h2d/ScaleGrid.hx

It works like `tileBorders` but allows tiling of the center of the ScaleGrid.

Added "tileCenter" support to ScaleGrid

---

hxd/fmt/fbx/BaseLibrary.hx

Newer Blender versions output scale factor as `0.9999999776482582`, that turns into 0 by Heaps (why it's even floored?), causing `scaleFactor` to become 0 and do lots of NaN issues.

Fix Blender fbx model scaling (again)

---

hxd/res/DynamicText.hx

Patterns containing characters that are not alphanumeric or underscores do not turn the containing text to a function anymore.
For example:
`<t>Some text ::value(hello)::</t>`
will be ignored

Make hxd.res.DynamicText ignore ::patte(rns):: that are not alphanumeric

---

hxd/res/Config.hx

Added two functions that allow you to use --macro to add either a pairedExension or map an extension to a class.
These functions seemed necessary as use the --macro on the variable threw a compiler error.  These functions are safer anyway.

Functions to allow extension config using --macro

---

h3d/scene/pbr/Light.hx
h3d/scene/pbr/PointLight.hx
h3d/scene/pbr/SpotLight.hx

Currenty in the JS examples all PBR lights are borkne, showing hard shadows without any color from lights.
The reason was that the WebGL shader for the light pass would pass the **occlusionFactor** member of `h3d.scene.pbr.Light` as **null**, as part of the pbrLightColor vector in the shader. 
For example a red light would show up as (1, 1, 1, null), instead of (1, 0, 0, 0), the fourth parameter being **pbrOcclusionFactor**. Particularly in the Directional lLight fragment shader mix sentence (pixelColor.rgb += direct * shadow * mix(1, occlusion, pbrOcclusionFactor););
Here is the Result for the types of values this would shoot out on certain vairables in Spector.js (notice the null value)
This made Webgl not know what to do and mark the whole color result in the shader as 0, e.g. black. …

Fixed: PBR Directional, Spot and Point lights broken in Javascript target due to null vallues in shaders.

---

hxd/snd/webaudio/Driver.hx

The WAV file specification mentions that 8-bit samples are stored as unsigned int, whereas bigger bit depths (16-bit and above) are stored in signed ints. 
* See here: https://www.lightlink.com/tjweber/StripWav/Canon.html for details.
And in JS, the webaudio AudioBuffer specification requieres to change the sample rate to a 32-bit float value in the [-1, 1] range.
* See here: https://developer.mozilla.org/en-US/docs/Web/API/AudioBuffer
The webaudio Driver.hx file assumes that the forma is in the [-128, 128] range and divides by 255. This works in 16-bit files, but because of the specification, its actually stored in [0, 255], with 128 being the midpoint, dividng by 255 will cause glitches in the sound as its being calculated incorrectly. 
Changing the way the sample is calculated for JS …

Fixed: 8-bit WAV files playing with glitches due to incorrect sample rate calculation

---

h2d/TextInput.hx

Fixes a crash when moving the mouse outside the input box while selecting:
https://github.com/HeapsIO/heaps/pull/1089#issuecomment-1232760687

Fix multiline TextInput when moving selection outside of TextInput

---

h3d/scene/CameraController.hx
hxd/Window.hl.hx
hxd/Window.hx
hxd/Window.js.hx
hxd/impl/MouseMode.hx
samples/MouseApi.hx

Integrates newly added mouse handling APIs into Heaps.
Adds 3 new features to `hxd.Window`:
* `mouseClip` - would restrain the mouse position within the window boundaries (actually extremely important for RTS games when using multi-monitor setup, so I expect to see that being added in Dune/Wartales/Northgard ;) Nothing is more infuriating than accidentally unfocusing the game because you moved the mouse a bit too fast and instead of stopping at the screen edge you end up clicking outside of the game)
* `mouseMode` - the mouse movement input mode.
* `setCursorPos` - what it says on the tin. Allows manipulating user cursor position. Also useful for Relative mouse mode, since real mouse position is undefined when relative mouse mode is enabled due to backend differences.
* `mouseLock` is …

Implement mouseClip and mouseMode API

---

hxd/Window.js.hx

Fixes an issue with mouse positioning being wrong in case window got resized but canvas didn't. 
Honestly entire mouse positioning should be rewritten and not rely on canvas bounding box arbitrarily fetched at resize events/init. Mouse input likely also will bug out in case of window scroll and canvas being not in the window-position of the bounding box.

JS: Fix input bugs with window resize.

---

h3d/mat/Pass.hx

It seems that in a previous update, a small mistake in the Multiple blend mode was introduced. This fixes it so that Multiply works properly.

Fix multiply blend mode

---

hxsl/Macros.hx

Started seeing below error on a product after updating to latest master. Reproduced with a blank project with only a call to hxd.Res.initEmbed()
```
/home/leo/dev/heaps/hxsl/Macros.hx:316: lines 316-322 : Object requires field ret
/home/leo/dev/heaps/hxsl/Macros.hx:316: lines 316-322 : For function argument 'f'
```

Add void return for hxsl setParamIndexValue and setParamFloatValue

---

hxsl/Checker.hx
hxsl/Dce.hx

Allows writing to array types as it is legal in both GLSL(+WGL) and HLSL. 
Feature requested by tee from Discord.
Same as #1127 I tested it on SDL, DX and JS targets, and there are no compatibility issues.
Test shader used:
```haxe
class WriteShader extends hxsl.Shader {
static var SRC = {
var pixelColor: Vec4;
function fragment()
{
var p:Array<Vec2,3> = [vec2(0.0),vec2(0.0),vec2(0.0)];
var i = 0;
p[i]=vec2(1.0,1.0);
var g = vec2(1.0,1.0);
p[1]=g;
pixelColor = vec4(p[0].x,p[1].y,p[2].x,1.0);
}
}
}
```

[HXSL] Enable ability to write to arrays.

---

h3d/Quat.hx
hxsl/Ast.hx

I'm changing resolution behavior in https://github.com/HaxeFoundation/haxe/pull/11168, which requires two adjustments:
1. Because enum constructors are no longer prioritized over types, the lexical order matters. Our resolution algorithm specifies that when importing a module, the first occurrence of an identifier in that module is the one we resolve to. This makes it necessary to declare `TExprDef` _before_ `TVar` so that we resolve to `TExprDef.TVar` instead of the `TVar` typedef.
2. The situation in Quat.hx is very strange, see https://github.com/HaxeFoundation/haxe/pull/11168#issuecomment-1517250449 for an explanation.
Both changes should not affect anything in other Haxe versions.

Adjust to upcoming Haxe resolution changes

---

h2d/TextInput.hx

The idea is to add support software keyboard on some platforms (e.g. console or mobile) for all TextInput created, with a single var `h2d.TextInput.showSoftwareKeyboard` to be assigned at the start of a program.
It can then be disable in individual TextInput, if needed, by setting `useSoftwareKeyboard` to false.
When `h2d.TextInput.showSoftwareKeyboard` is set, it will be called when TextInput is focused. After the input or canceled, the TextInput will be automatically blur to allow focus it again.

Added the possibility to specify and auto-call a software keyboard for all TextInput

---

hxd/fmt/pak/Build.hx
hxd/fmt/pak/Writer.hx

This option will, during pak generation, add padding of "0"s at end of Data and Header, to align the beginning of each block of Data.
This can ease binary comparison in some situation.
Tested on hl.

hxd.fmt.pak.Build: add option align

---

hxd/Pad.hx

In `onEvent()`, `e.controller` is based on `index` instead of `sp.id`, and `sp.id` is not guarantee to be the same as `index` (when index=0, sp.id=1). As we use `pads.get`, the key value should be `index` instead of `sp.id` in `initPad()`. The previous implementation can cause problem when more than 1 Pad is connected to the system: the 2nd one can cause the 1st one disconnect.

Pad SDL: use index in pads mapping

---

hxd/Window.hl.hx

When setting flag -D usesys, only one single Window will be created by System.start, it should be consider having always focus.

Let Window.isFocused return true when usesys.

---

hxd/res/FileTree.hx

This should get rid of the following warnings:
```
/usr/share/haxe/lib/heaps/git/hxd/Res.hx:4: characters 1-8 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
```

Don't rely on deprecated annotation to declare extern fields

---

h3d/impl/Driver.hx

b30ab26 broke compilation for js this commit addresses that,
I just made a guess for the usegl case.

added Texture.startingMip for js and usegl targets too

---

hxd/snd/Mp3Data.hx

Fix compilation error due to https://github.com/HaxeFoundation/hashlink/pull/629 (remove unneccecary arguments from mp3_open)

Fix hl mp3_open signature

---

hxd/Pad.hx

This commit revert #1154 #323 .
It fix error of pad event id after disconnect and reconnect (new), and allow multiple pad to be connected to the system (what was fixed by #1154).
However, it does not fix the double init in #323 (Fixed SDL double init), but I couldn't reproduce the error in a normal workflow.
The reason behind that is the e.controller is different in GControllerAdded (device id) and others events (joystick id). The joystick id is used to reference pad in pads (instead if device id), so pads.remove in GControllerAdded  will remove the wrong pad.

Fix SDL pad reconnect after disconnect event error

---

hxd/fmt/fbx/BaseLibrary.hx

- Fixed fbx import from Blender (we now apply units on translations)
- Fixed fbx import from 3DS Max (when root objects had translations, result hmd was different from input fbx)

fix fbx import (blender & 3ds max)

---

h3d/prim/ModelCache.hx

This used to more or less work but caused weird issues, so now `bind` can't be used with optional args
See https://github.com/HaxeFoundation/haxe/pull/11533

Cannot use bind with optional arguments

---

h2d/Font.hx

In https://github.com/HeapsIO/heaps/commit/e1e6e4a5f4c6c163975e427fd64d0a157b210eff `h2d.Font.resizeTo` was changed to scale by a ratio relative to initial size. This has a problem: For a font with initial size 12 `resizeTo(24)` scales it by a ratio 2. If `resizeTo(24)` is called again, we should expect no change in font size, but the ratio is again 2 because it is relative to initial size (12). The font is actually resized to 48.
This change simply reverts to previous `resizeTo` behavior. `initSize` cannot be entirely removed because it is used by `hxd.fmt.bfnt.FontParser`.
For the original issue "narrow chars becoming more narrow when resizing font", I was not able to replicate that. I tested by repeatedly scaling DefaultFont down to smaller values, and comparing the result to a font …

fix h2d.Font.resizeTo scaling

---

h3d/impl/RenderContext.hx
hxsl/DynamicShader.hx
hxsl/Macros.hx
hxsl/Shader.hx

When a param is a Int, use `getParamValue` makes unnecessary cast from Int to Dynamic, which means a lots of alloc (at least in HL target). Add `getParamIntValue` (similar to `getParamFloatValue`) to fix this.
`SetParamValue` for Int seems less critical and I don't know how to manage DynamicShader, so I didn't added it.

Prevent cast int to Dyn in Shader's getParamValue

---

hxd/Window.hl.hx

Heaps has several ways of doing window callbacks implemented, so I'm open to changing this call pattern; in this case we're using the same system as onClose (a dynamic function) but there's no need for a retval and we can't block the result so the calling pattern is simplified significantly.
The motivation for this feature is to allow multi-window apps to manage report their positions back to an underlying manager (in our case ImGui). This allows eg multi-window viewports to function.

add window move callback

---

h2d/domkit/BaseComponents.hx

How to use:
my-element {
filter: glow(none, @radius, @gain, @quality);
}
my-other-element {
filter: glow(@color, @alpha, @radius, @gain, @quality, @smoothColor);
}

Adding possibility to use glow filter reusing the color from the base texture.

---

h3d/mat/Material.hx

Cloning a material currently keeps a shared reference of color (Vector4). This can lead to unexpected results, when for instance calling `setColor()` on a cloned material all objects change to the same color.

Clone color vector in material clone function

---

h2d/TextInput.hx

This fixes some bugs in h2d.TextInput when `multiline` is set to true. These changes are isolated to `moveCursorVertically` which is gated behind `multiline`, so they should not affect the control when in the much more common single line mode.
* Fixes moving up/down a line when at the beginning of a line
* When moving up from the top line, move to the beginning of the line. Same behavior with down on the last line (moves to end of line)
* Fixes a bug when moving to a line that is hard wrapped shorter than the current position
I started making these changes due to a crash that was fixed in a recent commit, so it might be worth double checking this doesn't break other uses of this control, or collide with changes from others working on this feature. @robShiro

Fix bugs in multiline text input

---

h3d/impl/GlDriver.hx
h3d/impl/RenderContext.hx
hxd/fmt/hmd/Library.hx

Heaps change for
- https://github.com/HaxeFoundation/haxe/pull/11568
Require also latest hashlink `hl_ver >= version("1.15.0")` for std API.
Do not merge yet, until I'm sure + sync internal haxe version first.

[hl] change for haxe hl.NativeArray for Vector

---

.github/workflows/sync_wiki.yml

Will run daily at midnight UTC.
There are currently merge conflicts which need to be resolved before this will work, see: https://github.com/HeapsIO/heaps-doc/pull/97

Add github action to automatically synchronize wiki

---

CHANGELOG.md
h2d/Object.hx

Fix incorrect implementation of Object.move()
defails: https://github.com/HeapsIO/heaps/issues/1246

fix h2d.Object.move implementation

---

hxsl/HlslOut.hx

Wrong argument was used to determine required vector size on HLSL generator for texel fetch operation. 
Fixes #1255

Fix HLSL texel fetch

---

hxsl/SharedShader.hx

Live reload did not respect lack of `hscriptPos` flag, causing compilation error, as it tried to call a function on a type that didn't have it.
fix #1261

Respect hscriptPos flag for shader live reload

---

hxsl/Cache.hx

Dumps shaders into a `window.shaders` variable when `shader_debug_dump` is set and compiled under HTML5 without `sys`. Allows debugging shaders under HTML5 when sys target is not available.
Courtesy of today discord fun times of having to extract shader dumps from dev who only target HTML5 and is too deep in target-specific hooks to compile to HL.

Support shader_debug_dump flag on non-sys JS target.

---

.gitignore

Adds `/shaders` directory to .gitignore, so when `shader_debug_dump` is set while working on library itself it won't show up in git. (My setup workspace root for issues/features is in Heaps directory)

Ignore shader dump folder in git

---

h3d/mat/PbrMaterial.hx
hxd/fmt/fbx/HMDOut.hx
hxd/fs/Convert.hx
hxd/fs/FileConverter.hx

Add `hasLocalParams` and `computeLocalParams` in Convert, which allows specify additional parameters than the params in `props.json`.
In this specific use case, it allows configuring, by material, option `ignoreCollide` (only if the node `collide` is present in fbx->hmd conversion rule in `props.json`).
Related commit : https://github.com/HeapsIO/heaps/commit/07cf21e892533eaa0baece22eb390aeeea664e90

Convert: add localParams for collide per mat in hmd

---

hxsl/Ast.hx
hxsl/Checker.hx
hxsl/Dce.hx
hxsl/Eval.hx
hxsl/GlslOut.hx
hxsl/HlslOut.hx
hxsl/Linker.hx
hxsl/Printer.hx
hxsl/Serializer.hx
hxsl/Splitter.hx

The proverbial footgun. Introduces `Syntax.code` to HXSL.
Rationale is that feature being primarily for rare cases where HXSL doesn't offer some very specific language feature (from recent examples - no access to GLSL `GL_FragDepth`), but user needs access to it. Being able to inject raw language code is much less work than having to somehow implement those features. Additionally it gives partial resolution to all those people in discord asking if they can just use raw GLSL/HLSL for their shaders.
Personal reasoning: I prefer giving the user options to shoot themselves in the foot if they so wish. If they want to do some weird stuff with shaders that HXSL can't do out of the box and likely will break - let them, it's their feet, not mine.
The implementation is somewhat volatile, but …

Implement HXSL Syntax.code support

---

h2d/Scene.hx

Currently, there is an issue with the OpenGL driver when using `h2d.Scene.captureBitmap`. When it sets the scissor bounds to the viewport bounds, `GlDriver.curTexture` incorrectly refers to the current texture rather than the texture being rendered into, causing the scissor box to potentially use an incorrect position. I will note that the DirectX driver has no problem here because it doesn't need to alter the scissor box if it's rendering to a texture, which the OpenGL driver needs to do.
I have fixed this by simply reordering some function calls in `h2d.Scene.captureBitmap` to ensure the correct framebuffer will be set when `setRenderZone` is called.

Fix incorrect scissor box in h2d.Scene.captureBitmap

---

hxd/System.hl.hx

With SDL + mouse relative mode, when an exception is thrown in `reportError`, the SDL window keep the mouse in relative mode (mouse stay at the center of the window), which prevent user clicking freely on "Continue" in the pop-up `hl.UI.Window`, and user can only leave the situation with Alt-Tab.
Additionally:
- Forcing `hl.UI.Window` take focus (`SetFocus`) in native C code does not seems to have an impact, probably because it's not considerer as a standalone window.
- I cannot repro with DirectX
This PR manually set SDL in Absolute mouse mode before pop-up window, and restore it afterward.

[hl/Win] Prevent SDL stay in relative mouse mode on exception

---

h2d/filter/Blur.hx

When blur-based filters (such as outline) have a small radius (<1) - it causes the outline to be cut off due to undersized texture.
Ceiling `boundsExtend` fixes that issue. 
UPD: Changed to ceiling `radius` when assigning `boundsExtend` so it would extend uniformly regardless of radius value.

fix: Blur-based filters under-extend on small radius

---

hxd/fs/SourceLoader.hx

On Console (Test on Switch), call of sys.io.Process trigger that error : `error : undefined symbol: hl_process_stdin_close`
It's fine because we don't need it on console. But in the SourceLoader.hx there is a call of it keeped in console. 
I place a test on preprocessor usesys toi avoid that.

Fix Switch build failed 
