HeapsIO/heaps

doc/ref.html

cleans tags ;
describes h2d.Text ;
describes h2d.Font ;

Reference documentation: Displaying Text

---

hxd/BitmapData.hx

as per #105 it seems this check is no longer needed

remove haxe version check

---

h3d/impl/Driver.hx
h3d/impl/GlDriver.hx
hxd/BitmapData.hx
hxd/Stage.hx
hxd/System.hx

I've only tested it with this sample https://github.com/ncannasse/heaps/tree/master/samples/basic
The `hxml` to get it to work is:
```
-cpp bin
-main Main
-lib heaps
-lib openfl
-lib lime
-D lime-openal
-D openfl-next
-D lime-cairo
-D lime-opengl
-D native
-D lime-native
-D lime-curl
-D openfl-native
-D windows
-D desktop
-D resourcesPath=../res
--macro include('h3d')
--remap flash:openfl
```
And I had to comment out these lines for it to run:
https://github.com/ncannasse/heaps/blob/master/h3d/shader/AmbientLight.hx#L31
https://github.com/ncannasse/heaps/blob/master/h3d/shader/AmbientLight.hx#L35
https://github.com/ncannasse/heaps/blob/master/hxsl/Linker.hx#L365

Add support for openfl/lime

---

h2d/col/Voronoi.hx

getNeighborIds -> getNeighbors (retourne les points)
+getNeighborIndexes -> retourne les index des cellules

Voronoi : GetNeighborIds

---

hxd/fs/BytesFileSystem.hx
hxd/res/Atlas.hx
samples/comps/Comps.hx
samples/shadows/Main.hx

I was getting these error when trying to build all samples:
```
hxd/fs/BytesFileSystem.hx:57: characters 73-112 : Could not determine type for parameter T
hxd/res/Atlas.hx:43: characters 72-80 : Cannot create closure on abstract inline method
```
This PR fix the build of the samples in all.hxml.

Fix compilation

---

h3d/impl/NullDriver.hx
h3d/shader/Texture2.hx

Not sure if I'm doing something wrong in my setup, but the basic sample wasn't building until I made these fixes.

Compile Fixes

---

h2d/Text.hx
hxd/res/Font.hx
hxd/snd/NativeChannel.hx

Add support of sound on lime (using lime_openal) and small fixes for texts

Sound on lime

---

h2d/Console.hx
h2d/Sprite.hx
h2d/SpriteBatch.hx

Few shortcuts and utils functions.
@deepnight

[MotionTwin] Deepnight changes

---

h2d/Console.hx

Let hide and show by code.
The log wasn't working with Haxe 3.2.1 because the UString class and this: https://github.com/HaxeFoundation/haxe/issues/4426

Console hide, show and fix log

---

hxd/Stage.hx

- add button number to mouse down in webgl
- add button number to mouse up in webgl
- disable context menu for canvas

Add Mouse RightButton Support to webgl

---

hxd/net/LocalHost.hx
hxd/net/Macros.hx
hxd/net/Serializer.hx

- Fix use of another NetworkSerializable class as paremeter of a @:rpc function
- Allow UInt serialization
- Fix serialization of String with utf8 characters
- Add optional parameters in LocalHost.openNewWindow()

hxd.net fixes

---

hxd/Pad.hx
hxd/System.hx
samples/Pad.hx

Adds:
- support for hxd.Pad on hlsdl
- hxd.Pad.onDisconnect method
- a basic hxd.Pad sample

HL SDL Pad

---

hxd/net/Macros.hx

- Fix for  unserialization of PObj with more than 8 fields
- Fix for (some) conflicts between Class name and imported Enum value

hxd.net.Serializer fixes

---

hxd/fmt/grd/Data.hx
hxd/fmt/grd/Reader.hx
hxd/res/FileTree.hx
hxd/res/Gradients.hx
hxd/res/Loader.hx

Adds support for ".grd" files in hxd.res
- toTexture("gradientName") creates a texture for the specified gradient
- toTextureMap() creates all gradient textures
- toTileMap() creates all gradients into the same texture and returns sub-tiles

Photoshop gradient files support

---

h3d/impl/GlDriver.hx
hxd/snd/NativeChannel.hx

Fix some lime compilation issue. Need this [PR](https://github.com/openfl/lime/pull/864) also from Lime to have compilation fully working. Also need the latest GIT version of hxcpp and haxe.

Fix lime compilation

---

hxd/snd/NativeChannel.hx

Last PR I did, fixed the compilation issue, but still wasn't working properly on lime target.

Fix NativeChannel with Lime

---

hxd/snd/ALEmulator.hx

@ncannasse found another issue with #220

close #220

---

hxd/impl/PathFind.hx

fill the array with 0 on JS

---

h2d/Flow.hx

Renamed clientWidth/Height to innerWidth/Height
Added outerWidth/Height

innerWidth / outerWidth

---

h2d/col/Voronoi.hx

Based on https://github.com/gorhill/Javascript-Voronoi
It now throws an exception for some specific not handled values (instead of infinite loop)

Voronoi update

---

h2d/Text.hx
hxd/Charset.hx

- Unified implementation for h2d.Text and h2d.HtmlText
- Removed punctuation from break chars, added CJK
- Break line on break char only if required

Fix split text

---

hxd/Key.hx
hxd/Stage.js.hx

- Fixes ERelease/EPush events on JS for middle, back and forward buttons.
- Adds access for these buttons via hxd.Key (all platforms).

Improved handling of mouse buttons

---

hxd/Stage.hl.hx

Requires https://github.com/HaxeFoundation/hashlink/pull/67

Handle hlsdl Quit events via Stage.onClose

---

h2d/col/IBounds.hx

IBounds.clone returns IBounds

---

hxd/Pad.hx

Uses `dx.GameController` (hldx) and `haxe.GameController` (usesys) common interface

hxd.Pad refactoring

---

samples/SampleApp.hx

Fix samples for https://github.com/HeapsIO/heaps/commit/022646f15f7124455f3e40424a01ec5c2cc5e444

SCN to HSD in sample

---

hxd/App.hx

here's some contribution :)
i'm still not sure what exactly is passed to the `update` method, so I just said it's "normalized time since last frame", feel free to edit this (and all the other comments ofc).

add some api docs for hxd.App

---

h2d/Anim.hx
h2d/Bitmap.hx
h2d/Drawable.hx
h2d/Scene.hx
h2d/Sprite.hx
h2d/Text.hx
h2d/Tile.hx
h2d/TileGroup.hx

It's easier when figuring out what kind of type is required, also avoids issues like [this](https://github.com/HeapsIO/heaps/issues/302).

Add some (return) types

---

.travis.yml

😝 https://travis-ci.org/HeapsIO/heaps/builds

Receive notifications for failing builds

---

README.md

There you go 👍 
.. better fix the errors before someone sees it 😉 
[![Build Status](https://travis-ci.org/HeapsIO/heaps.svg?branch=master)](https://travis-ci.org/HeapsIO/heaps)

Travis icon

---

h3d/scene/CameraController.hx

Allow overriding the behaviour when subclassed

[CameraController] Extract fov, zoom, rotate, pan

---

h3d/impl/DirectXDriver.hx

Fixed DirectXDriver in debug

---

h3d/impl/DirectXDriver.hx

Fixed DirectX (setRenderTarget in begin)

---

h2d/KeyFrames.hx
hxd/fmt/kframes/Data.hx

- Added support for image sequence
- Added smooth property
- Fixed when multiple layers have the same name
- Fixed when scaleX != scaleY
- Fixed animated anchorPoint

Improved Keyframes

---

.travis.yml

BTW, if you add me to the project, I can look into setting up hlc testing in the CI too.

[TravisCI] test 3.4.7 and 4.0.0-preview.3 too

---

h3d/Matrix.hx

The get argument was unused and the set was doing a get.

Fix matrix get/set position

---

h2d/HtmlText.hx
h2d/Text.hx
samples/HtmlText.hx

HtmlText handle TextAlign correctly

---

hxd/snd/NativeChannel.hx

Fix to get audio working on mobile safari (and probably other mobile browser)

Fix suspended audio context on mobile

---

CHANGELOG.md
h2d/Graphics.hx

added rotationAngle to h2d.Graphics.drawEllipse

---

hxd/System.hl.hx
hxd/Window.hl.hx

touch events in HL

---

h3d/prim/Quads.hx

After some difficults to create a Quad primitive (i was thinking of CW or CCW for vertices), i've been told how to do. So i complete the doc for the next people asking.

Add comments to Quads.hx

---

hxd/res/Config.hx

Don't ignore ogg files in Res if stb_ogg_sound present.

---

h2d/Graphics.hx

Fix #529 
Currently `h2d.Graphics` flush it's data after initial allocation only after buffer is filled completely (`1 << 15` vertices), which is not an expected behavior. This change forces Graphics to flush new buffer data on `sync()`.
Note: Build failed due to travis not being able to set up haxelib dependencies.

Reflush buffers on h2d.Graphics when new data added.

---

h3d/impl/GlDriver.hx

Make it possible to disable WebGl2

---

h3d/prim/Quads.hx

To have a similar functionality like `Polygon.translate`

Add Quads.translate

---

hxd/fs/LocalFileSystem.hx

symlinks in resources dir fix

---

h2d/Graphics.hx

I think it is very useful thing.
For example cooldowning abilities you used in a rpg. Ability icons are square, so we need a square pie :)
Screenshot:

added: drawRectanglePie()

---

h2d/Layers.hx

Please let me know if I used the wrong code style or anything like that.

Add documentation to `h2d.Layers`

---

hxd/Window.js.hx

See: https://github.com/HeapsIO/heaps/commit/9bffc63ae92d3577a349b6911a7523eba7c13c92

Fixed game-related key propagation issue

---

hxd/File.hx

Added JS support for the File.browse() method (it uses a temporary <input/> element, but that's how it "works" on JS).

Added JS support for hxd.File.browse() ("open file" dialog)

---

hxd/snd/webaudio/AudioTypes.hx
hxd/snd/webaudio/Driver.hx
hxd/snd/webaudio/LowPassDriver.hx
hxd/snd/webaudio/SpatializationDriver.hx
samples/Sound.hx

Apparently VSCode didn't push the commit with fixes that actually implement effects and make pitch work more adequatly and I didn't notice it, sorry.
Implements stuff in regard of effects described in #711 
Note: Travis failed because haxelib error on SSL. Again. It does it sometimes. 4.0.0 passed, dev didn't due to haxelib not being able to install deps.

Audio fixes followup: Missing webaudio commit

---

h2d/Slider.hx

fixes https://github.com/HeapsIO/heaps/issues/705

Added slider handle to slider bounds

---

h3d/Engine.hx
hxd/Window.flash.hx
hxd/Window.hl.hx
hxd/Window.hx
hxd/Window.js.hx

closes https://github.com/HeapsIO/heaps/issues/730

added displayMode and title property to window. deprecated setFullscreen

---

hxd/res/FileTree.hx

Fixes Res completion with files under "final" name as it's a keyword now.

Fix final keyword as file name

---

h2d/Graphics.hx

The method signatures are similar to AS3 API:
https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/Graphics.html
The implementation is taken from IvanK Lib:
http://lib.ivank.net/?p=documentation

Added curveTo and cubicCurveTo methods to h2d.Graphics

---

h2d/Graphics.hx
h2d/col/Line.hx

Line.angle()  - The angle between a line and the x-axis
Line.length()  - Distance between line points

Updated h2d.col.Line with angle() and length() methods

---

h3d/prim/Circle.hx
h3d/prim/Disc.hx

Example: http://tmp.disktree.net/heaps-primitives/  
Use `W` to toggle wireframe.

add Circle primitive

---

hxd/File.hx

Browser timeout fix

---

hxd/fmt/fbx/HMDOut.hx

Fix typo in HMDOut.hx

---

h2d/Scene.hx

Fix typo in Scene.hx

---

h3d/impl/Stage3dDriver.hx

We actually need track_alloc to access h3d.Buffer.allocPos

Fix Stage3D build failing with -debug

---

hxd/net/BinaryLoader.hx

Btw, there's no way to do a simply HTTP async url request in Haxe? 🤔

Added a throw in BinaryLoader for unsupported platforms

---

samples/Polygons.hx

In this PR, i add an example of polygons from h3d.prim : 
- Grid
- Cube
- Cylinder
- Disc
- Geosphere
- Sphere
I also try to add arrow key movements but i'm not sure of the implementation.
Feel free to criticize.

Add Polygons example: show examples of all poly in h3d.prim

---

hxsl/AgalOut.hx
hxsl/Ast.hx
hxsl/Checker.hx
hxsl/GlslOut.hx
hxsl/HlslOut.hx
hxsl/MacroParser.hx
hxsl/Macros.hx
hxsl/Serializer.hx

Resolves #810
There will be conflicts with [my other pull request](https://github.com/HeapsIO/heaps/pull/812) because some code changes are at similar places. But should be easy to resolve.

add Mat2 type

---

h2d/TextInput.hx

This PR implements most points from #819, except multiline support which is more involved. Maybe a separate issue should be open for multiline TextInput?

TextInput shortcuts

---

h2d/col/Matrix.hx

* Add skewing transformation support:
`initSkew(sx, sy)`, `skew(sx, sy)`, `skewX(sx)`, `skewY(sy)`
* Add per-axis methods:
`translateX(x)`, `translteY(y)`, `prependTranslateX(x)`, `prependTranslateY(y)`, `scaleX(sx)`, `scaleY(sy)`

Expand 2D matrix API

---

h3d/impl/RendererFX.hx
h3d/scene/Renderer.hx
h3d/scene/pbr/LightSystem.hx
h3d/scene/pbr/Renderer.hx
h3d/shader/pbr/ToneMapping.hx
hxd/fmt/fbx/BaseLibrary.hx

Pbr refactor

---

h2d/col/IBounds.hx
h2d/col/IPoint.hx

Fixes copy-paste bug mentioned in https://github.com/HeapsIO/heaps/pull/842#issuecomment-652587095

Fix copy-paste bug for IPoint/IBounds return types

---

h2d/RenderContext.hx

Add option "heaps_buffering" to enable buffering in emitTile.

add option to enable buffering for emitTile

---

h2d/HtmlText.hx
h2d/Text.hx
hxd/Charset.hx

Mark Chiisai Japanese characters as complementChar that must not be broken for a new line

Breaking line japanese rules

---

h2d/col/Point.hx

Nit about not actually "returning" anything :)

Tiny docstring fix for Point.scale()

---

hxd/snd/Manager.hx

Channel gets shifted after multiple pause/resume

fix: prevent from shifting channel position

---

h2d/HtmlText.hx
h2d/domkit/Style.hx
h2d/filter/AbstractMask.hx
h3d/scene/Renderer.hx
h3d/scene/pbr/Renderer.hx
hxd/fs/FileConverter.hx
hxd/impl/Api.hx
hxd/inspect/PropManager.hx
hxd/inspect/PropTools.hx
hxd/inspect/ScenePanel.hx
hxd/inspect/SceneProps.hx
hxd/res/DynamicText.hx
hxd/snd/LoadingData.hx
hxsl/GlslOut.hx
hxsl/HlslOut.hx
hxsl/Printer.hx

* Rename `Api.is` to `Api.isOfType` - fixes `is` warning.
* Fix travis for haxe-dev on DebugMode.Full. I have to note that this is a regression compared to 4.1 and it should resolve it as DebugMode abstract, but for whatever reason it doesn't.
Note: Wait for travis checks to complete before merge in case it will fail at something else.

Fixup for Haxe4.2+

---

hxd/System.hl.hx

Now that Haxe 4.2.1 came out with MainLoop fix, the simplified version of the previous fix PR is here. Supersedes previous PR.
For obvious reasons won't work on 4.2.0, and requires 4.2.1+
close #927 ; fix #922

Fix haxe 4.2 update loop

---

samples/Input.hx

Add an touch screen detection example to "Input" sample.
Hopefully this helps with visibility: https://github.com/HeapsIO/heaps/issues/943

Detect touch screen in sample

---

hxd/Window.js.hx

Use mouseLock variable and Point Lock API to implement a new mouse movement system.
We can now call requestPointerLock to go into lock mode : the mouse cursor is hidden and cannot move, but the mouse movement is still registered.

Lock Mouse Editing Implementation

---

hxd/Window.js.hx

Call resize on window binded to js element and not every 100ms.

Better resize check

---

h3d/scene/LightSystem.hx
h3d/scene/Renderer.hx
h3d/scene/pbr/LightBuffer.hx
h3d/scene/pbr/LightSystem.hx

Fix driver crash accessing disposed forward's light buffer. Prevent

---

hxd/Window.hl.hx

Window size from window returned by SDL (for Android)

---

h3d/scene/Graphics.hx
hxd/res/Image.hx

Added floating point setter for color.  Adds ease of access and precision.

Added floating point color setter

---

hxd/snd/Manager.hx

this should fix https://github.com/HeapsIO/heaps/issues/1034

pausing and setting position of audio seems to work now

---

h2d/Video.hx
h3d/pass/PointShadowMap.hx

AV1 codec + webm container support only

Refactored the video support for hashlink using the hlvideo library

---

h3d/mat/TextureChannels.hx
hxsl/Eval.hx
hxsl/Printer.hx

Also fix oversight from https://github.com/HeapsIO/heaps/commit/962fda7464777793de59058bbdce57fb863cde19

Make compatible with latest Haxe

---

hxd/res/Config.hx
hxd/res/FileTree.hx

Added a Map to res Config to ignore a specific set of directories (eg. backups or other cache related things)

Added hxd.res.Config.ignoredDirs

---

hxd/Pad.hx

works in chrome using vibrationActuator, not sure about safari and firefox

Added gamepad vibration support for browsers

---

h2d/TextInput.hx

These changes let you set a "multiline" property on the TextInput. Doing so will change the behavior of "Enter" from blurring, to adding a newline character to the text. The change also properly handles clicking on different lines, text wrapping, selecting multiple lines, etc...

add multiline support for TextInput

---

h3d/anim/Animation.hx

Fix spelling error in error mesage in Animation.hx

---

hxsl/Cache.hx
hxsl/Eval.hx
hxsl/Linker.hx
hxsl/Printer.hx
hxsl/Splitter.hx

Refactor Splitter

---

h2d/Object.hx

minor comment change

---

h2d/Font.hx
h3d/mat/Material.hx
h3d/mat/PbrMaterial.hx
h3d/scene/Object.hx
h3d/scene/pbr/Renderer.hx
h3d/shader/Buffers.hx
h3d/shader/pbr/Slides.hx
hxd/Direction.hx
hxd/Pixels.hx
hxd/fmt/hmd/Data.hx
hxd/fmt/kframes/Data.hx
hxd/impl/Allocator.hx
hxd/res/Image.hx
hxsl/DynamicShader.hx

~This also drops support for Haxe 3.~ There is already plenty of code in this repo using the Haxe 4 only syntax.
Fixes https://github.com/HeapsIO/heaps/issues/1148

Remove deprecated macros

---

h3d/prim/ModelCache.hx
hxd/fmt/hmd/Library.hx

Compatibility with the new prefab2 branch (https://github.com/HeapsIO/hide/tree/prefab2) using a compilation flag

New hide prefab system compat for heaps (-D prefab2)

---

h3d/impl/DX12Driver.hx
h3d/impl/Driver.hx

Suggest by @ncannasse in #1162

Move tmpBuff inside TextureData dx12

---

h2d/domkit/BaseComponents.hx
hxd/fmt/hmd/Reader.hx

See https://github.com/HaxeFoundation/haxe/issues/11187 / https://github.com/HaxeFoundation/haxe/pull/11168

Fix module resolution for Haxe 5

---

hxd/Timer.hx

Related to c9a15e15098921ee3efe21348c736c9ad2f79682

Update smooth factor description to reflect algorithm change

---

hxd/Pad.hx

In #1177 , The multi-init fix ( #323 ) have been removed , now add it in initPad

Move multi-init fix into initPad

---

h2d/domkit/BaseComponents.hx

How to use:
on a .less file you flip a tile used by a bitmap with
bitmap {
src-flip-x: true;
src-flip-y: true;
}

Adding srcFlipX and srcFlipY to BitmapComp

---

h2d/RenderContext.hx
samples/Camera2D.hx

The `h2d.Camera` instance is now tracked via `RenderContext.currentCamera` variable. This allows for much more flexible camera visibility filtering other than top-level layer filtering, as objects nested deep in the object tree now will be able to check which camera they are being rendered by during `drawRec` call and alter/prevent rendering when needed.
Motivation: While filtering by top-level layers works reasonably well, when more complex cases arise, like camera-specific effects nested in the object tree or camera-specific parameters for rendering like tint or alpha - it becomes clear that a way to check current active camera is required.
Additionally updated Camera2D sample:
* Fixed regression after `Layers.add` adding to top-most layer by default.
* Added a moving car sprite that …

Add current camera instance tracking to 2D RenderContext

---

h2d/TextInput.hx

Small fix to ensure inbound index when moving cursor vertically

---

h2d/domkit/Style.hx

This depends on this domkit PR:
https://github.com/HeapsIO/domkit/pull/55

Display line number next to properties on domkit inspector

---

h3d/impl/DX12Driver.hx
h3d/impl/DirectXDriver.hx
h3d/impl/GlDriver.hx
h3d/impl/RenderContext.hx
hxd/fmt/hmd/Library.hx

see discussions in https://github.com/HaxeFoundation/haxe/pull/11568

Revert "[hl] change for haxe hl.NativeArray for Vector (#1224)" and related commit

---

h3d/col/Seg.hx

h3d.col.Seg did not yet include z axis in the last case of the distance check.

h3d.col.Seg: Include z in distance check

---

hxsl/GlslOut.hx
hxsl/Linker.hx
hxsl/Serializer.hx

See https://github.com/HaxeFoundation/haxe/pull/11338

Fix for latest Haxe nightlies

---

hxd/net/RemoteConsole.hx
hxd/net/Socket.hx

A basic string-based local communication with TCP, allow typically Hide-game communication

Add hxd.net.RemoteConsole for local communication

---

h3d/Matrix.hx
h3d/Quat.hx
h3d/anim/BlendSpace2D.hx

Also added anim related helper functions to Quat and Matrix

[anim] Migrated BlendSpace2D from Hide to Heaps

---

hxd/snd/openal/Driver.hx

Requires hlopenal 1.16 and Openal-Soft 1.22.0

Openal Driver: reopen device on default device change
